### PR TITLE
Improve table

### PR DESCRIPTION
**Pull request by reeceshuttle**
This code will exclusively make the main tables for the paper depending on the script you run:
1. If you run `python scripts/analyze_results.py --results_dir <path to unzipped directory>/all_planning/`, It will make a table with `Pure Planning`, `Random Action Planning`, and `LLM Standard Planning`, each with nodes created, nodes expanded, and success.
2. If you run `python scripts/analyze_results.py --results_dir <path to unzipped directory>/all_open_loop/`, It will make a table with `LLM Standard`, `LLM Standard no Autoregress`, and`Random Actions`(we might want to drop `LLM Standard no Autoregress` from this table to be consistent with 1.), With each only getting their statistics for success. 
I have attached what the tables look like right now for reference.
Screen Shot 2022-09-25 at 4 49 56 PM

### CODE REVIEW

**Comment by tomsilver** [comment]
thanks very much, great work! one medium size thing before I hit you with a bunch of small things: can you add a row at the bottom of the tables that averages together all of the other rows?

**Comment by reeceshuttle** [comment]
> thanks very much, great work! one medium size thing before I hit you with a bunch of small things: can you add a row at the bottom of the tables that averages together all of the other rows?

Done. Here is what it looks like now: 
Screen Shot 2022-09-25 at 8 01 18 PM

**Comment by tomsilver** [comment]
excellent! okay now here's my list of small adjustments:
* I think my original suggestion for how to add column lines was maybe not the best because there are lots of little gaps everywhere. Can you mess around with the latex and see if you can remove those gaps? You may want to consult documentation for latex table making
* capitalize the environment names
* capitalize all of the approach names and do all caps for LLM
* center the approach names at the top of the columns
* remove the dashes in "llm-standard-random-plan"
* bold the new average row numbers
* change "llm standard no autoregress" to just "no autogregress" to cut down on all of the vertical white space in that column

thanks!!

**Comment by reeceshuttle** [comment]
Just finished implementing the changes you wanted and just pushed the code. When you run the code, the main graph and appendix graphs will be creaeted and printed(they will be labelled). Let me know if this makes sense/if it works on your end!

**Comment by tomsilver** [comment]
Looks perfect! Keeping this open for now because we'll probably add one more approach shortly (the randomization ablation)

**Comment by tomsilver** [comment]
great work. let's close this so we don't have to worry about resolving the checks, but we'll have it to refer back to in the pull request history when we want to use it again later.

**Pull request closed without merging**
